### PR TITLE
HotFix: Fix Ally invite sending to already allied nations.

### LINKED ISSUE #3749: Suggestion: The /n ally command should notify you if you are already allied
Basically abort the command with an error saying they are already allied. (Right now it sends the request anyway)

### PR DESCRIPTION
**Pull request by suneettipirneni**
#### Description: 

This fixes the issue where towny will still send invites to ally with nations even if they are already allied. This also removes the labeler workflow.
____
#### Relevant Towny Issue ticket:

Closes #3749 
____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

File: src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java [hunk 1]
```diff
@@ -26,6 +26,7 @@
 import org.bukkit.Material;
 import org.bukkit.block.Block;
 import org.bukkit.block.BlockFace;
+import org.bukkit.configuration.file.YamlConfiguration;
```
Comment (LlmDl) [inline src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java]: Unused import?

File: src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java [hunk 2]
```diff
@@ -37,6 +38,9 @@
 import org.bukkit.event.block.BlockPistonExtendEvent;
 import org.bukkit.event.block.BlockPistonRetractEvent;
 import org.bukkit.event.block.BlockPlaceEvent;
+import org.bukkit.inventory.ItemStack;
+import org.bukkit.inventory.meta.ItemMeta;
+import org.yaml.snakeyaml.Yaml;
```
Comment (LlmDl) [inline src/com/palmergames/bukkit/towny/listeners/TownyBlockListener.java]: Unused imports?

File: src/com/palmergames/bukkit/towny/command/NationCommand.java [hunk 3]
```diff
@@ -1735,10 +1735,12 @@ private void nationAlly(Player player, String[] split) throws TownyException {
 					ally = townyUniverse.getDataSource().getNation(name);
 					if (nation.equals(ally)) {
 						TownyMessaging.sendErrorMsg(player, TownySettings.getLangString("msg_own_nation_disallow"));
-						return;
+					} else if (nation.isAlliedWith(ally)) {
+						TownyMessaging.sendErrorMsg(player, String.format(TownySettings.getLangString("msg_already_ally"), ally));
```
Comment (LlmDl) [inline src/com/palmergames/bukkit/towny/command/NationCommand.java]: It's debatable whether the return statement should be put back in for the nation.equals(ally) and also added to your new if statement. I know it's supposed to pass over any non-usable names because it is sent a String[], but if you look at the cases below inside of the catch, if it is given an unusable argument it kills it with a return, rather than continuing to process the string. I would say put the returns in the try to match until all of the returns can be dealt with.

Comment (suneettipirneni) [reply src/com/palmergames/bukkit/towny/command/NationCommand.java]: The reason I removed the returns, is because it doesn't seem logical to have them when you think about it from the perspective of the player. For example

Nation1 is allied with Nation2
Nation2 is allied with Nation3

Player in Nation1 executes command `/n ally add Nation2 Nation3` 
Towny says you're already an ally and stops.

Now lets switch the order
Player in Nation1 executes command `/n ally add Nation3 Nation2`
Towny states that Nation1 is now an ally of Nation2
Towny then states Nation1 is already an ally with nation two.

^ There's a discrepancy in the results of these commands only when the order differs, which is confusing for the player. This discrepancy is caused by the order of the input.

By removing the `return` it removes this discrepancy, and simply "skips" and notifies if a nation in the input list if it's already allied, and then carries on to ally the other ones passed in. Therefore you can pass the nations into the command in any order and it should work as expected.
