### PR TITLE
Claiming & AreaSelectionUtil Fix Up.

### LINKED ISSUE #4395: Claim radius throws "Selected area not attached to edge"
### What steps will reproduce the problem?
1. creating a new town/plot
2. Standing either inside or outside of the plot
3. Command /t claim 4 or /t claim rect 4 

### What is the expected output?
1. To claim an area that is 9x9
2.
3.

### What is your Towny version?
Do not say "latest".
0.96.3.0

### What is your spigot/craftbukkit version?
Do not say "latest".
PaperSpigot 1.16.3

### Please use Pastebin.com to link the following files:

**Skipping these files is not an option. It is the easiest way to diagnose an issue ticket properly. If you do skip this step then your ticket will most likely be deleted and you will be asked to resubmit.**
1. Your full server startup from the logs\latest.log : https://pastebin.com/8rw7aaje
2. Your Towny config.yml (if using MySQL please remove password,) : https://pastebin.com/jQhMRgR9
3. Your townyperms.yml : https://pastebin.com/GXy5YRSQ
4. Your log's error : 

(optional) If this is to do with permissions, 
5. Your permissions file :

(optional) If this is to do with chat,
6. Your chatconfig.yml :
7. Your channels.yml :

### LINKED ISSUE #4427: ./t unclaim rect (number) not working
### What steps will reproduce the problem?
1. stand in a claimed area. (or claim it, in this case I did /t claim rect 3, it said it claimed, but also tried it in an outpost of an established town)
2. do /t unclaim rect (number) (I tried 3 and 4)
3. Towny says "[Towny] Selected Area contains no valid plots" and the land is not unclaimed.

### What is the expected output?
1.  Towny should unclaim the land.
2.
3.

### What is your Towny version?
Do not say "latest".
0.96.3.2

### What is your spigot/craftbukkit version?
Do not say "latest".
Paper 249 (1.16.3)

### Please use Pastebin.com to link the following files:
Llmdl said it was okay to skip the form.
He also said to reference his notes:

@Momshroom can you ticket that one, I think it might be related to https://github.com/TownyAdvanced/Towny/issues/4395
Don't worry about hte full form, just the version numbers

fwiw, /t claim rect DID work, but I was standing in the town at the time.
unclaim didn't

LlmDlToday at 3:46 PM
if you look at line 3493 of the TownCommand
which is 2 lines before the message you describe gets printed out.
it looks like we're filtering out all of the owned townblocks even though it's an unclaim
I dunno why we're filtering out owned townblocks though smh

LlmDlToday at 3:48 PM
no, I don't have the time atm to close it

but you can cite my notes

fixing this is probably going to need some testing
it's probably supposed to be filtering something but not owned blocks
probably so you cannot unclaim someone else's land

### PR DESCRIPTION
**Pull request by LlmDl**
#### Description: 

- Area selection util was also determining if something could be claimed, while it should have only been getting a shape of WorldCoords.
- Remove a pile of redundant stuff in the claiming code.
- Actually filter radius claims going too close to homeblocks.
- Make /plot nfs not work on PlotGroups and make use of unused language string.

Area selection changes:
- The `/t claim rect|circle #` commands both make perfect rings, with no half-made rings of claims. (Either a perfect square or circle.)
  - They will auto-lower the desired radius to accomplish this.
  - Results in a centered rectangle instead of claims being made primarily in the upper left corner.
  - Closes #4395.
- Claiming is now done using a spiral outwards from the stood-in plot.
  - Makes for perfect-looking claims when /t claim {auto|circle auto|rect auto}  is used.
- They will actually go to the last townblock available now.
- Removes the unneeded `/t unclaim outpost` from the AreaSelectionUtil.

____
#### New Nodes/Commands/ConfigOptions: 

____
#### Relevant Towny Issue ticket:

Closes #4427 
Closes #4395 

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

### CODE REVIEW

File: src/com/palmergames/bukkit/towny/command/PlotCommand.java [hunk 1]
```diff
@@ -445,18 +446,13 @@ public boolean parsePlotCommand(Player player, String[] split) throws TownyExcep
 						return true;
 					}
 					
-					if (!townBlock.getType().equals(TownBlockType.EMBASSY)) 
-						selection = AreaSelectionUtil.filterOwnedBlocks(resident.getTown(), selection);
-					else
-						selection = AreaSelectionUtil.filterOwnedBlocks(resident, selection);
+					selection = AreaSelectionUtil.filterOwnedBlocks(resident, selection);
```
Comment (LlmDl) [inline src/com/palmergames/bukkit/towny/command/PlotCommand.java:449]: Requires testing.

File: src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java [hunk 2]
```diff
@@ -85,34 +83,53 @@
...
 				}
 					
 				if (r > 1000)
 					r = 1000;
 				for (int z = -r; z <= r; z++)
 					for (int x = -r; x <= r; x++)
-						if (out.size() < available) {
-							WorldCoord wc = new WorldCoord(pos.getWorldName(), pos.getX() + x, pos.getZ() + z);
-							if (!wc.hasTownBlock())
-								out.add(wc);
```
Comment (LlmDl) [inline src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java:115]: This is the actual code that caused the issue with #4427, this selection tool is always assuming that you're going to be claiming land. Also below in the circle-shape selector.

File: src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java [hunk 3]
```diff
@@ -85,34 +83,53 @@
...
+						if (out.size() <= available) {
+							out.add(new WorldCoord(pos.getWorldName(), pos.getX() + x, pos.getZ() + z));
```
Comment (silverwolfg11) [inline src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java:132]: Can use `pos.add(x, z)` instead.

File: src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java [hunk 4]
```diff
@@ -141,27 +158,38 @@
...
 				if (r > 1000)
 					r = 1000;
 				for (int z = -r; z <= r; z++)
 					for (int x = -r; x <= r; x++)
-						if ((x * x + z * z <= r * r) && (out.size() < available)) {
-							WorldCoord wc = new WorldCoord(pos.getWorldName(), pos.getX() + x, pos.getZ() + z);
-							if (!wc.hasTownBlock())
-								out.add(wc);
+						if ((x * x + z * z <= r * r) && (out.size() <= available)) {
+							out.add(new WorldCoord(pos.getWorldName(), pos.getX() + x, pos.getZ() + z));
```
Comment (silverwolfg11) [inline src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java:192]: Could use `MathUtil.distanceSquared(x, z) <= MathUtil.sqr(r)` as an alternative.

File: src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java [hunk 5]
```diff
@@ -85,34 +83,53 @@
...
-				if (r > TownySettings.getMaxClaimRadiusValue() && TownySettings.getMaxClaimRadiusValue() > 0) {
-					throw new TownyException(Translation.of("msg_err_invalid_radius_number", TownySettings.getMaxClaimRadiusValue()));
+					if (TownySettings.getMaxClaimRadiusValue() > 0 && r > TownySettings.getMaxClaimRadiusValue())
+						throw new TownyException(Translation.of("msg_err_invalid_radius_number", TownySettings.getMaxClaimRadiusValue()));
+
+					// Calculate how many TownBlocks are needed to claim the radius. 
+					// Start blocks at 0 if the plot is unclaimed.
+					int neededBlocks = pos.getTownBlock().hasTown() ? 0 : 1;
+					for (int i = 1; i <= r; i++)
+						neededBlocks += i * 8;
```
Comment (silverwolfg11) [inline src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java:113]: Can replace for with a closed-sum formula. `neededBlocks += 4 * r * (r + 1) `

File: src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java [hunk 6]
```diff
@@ -21,48 +22,61 @@
...
-						tb.setOutpost(true);
-						out.add(pos);
-					} else {
-						throw new TownyException(Translation.of("msg_err_unclaim_not_outpost"));
-						// Lang String required.
-					}
-				}
-				if (tb.isOutpost()) { // flatfile skipper
-					out.add(pos);
-				}
```
Comment (LlmDl) [inline src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java:60]: Removed because we're doing the same thing anyways when someone does `/t unclaim`

File: src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java [hunk 7]
```diff
@@ -72,101 +86,178 @@
...
+				// Rethink how much of a radius will be used, as there's not enough available TownBlocks.
+				if (neededBlocks > available) {
+					r = 1; 
+					int total = 0;
+					while (available - ((r * 8) + total) >= 0) { // Radius 1 grabs 8 blocks, 2 grabs 16 more requiring 24, 3 grabs 24 more requiring 48, etc...
+						total += r * 8;
+						r++;
 					}
+					r--; // Finally reduce the radius by 1 (so that we have a perfect ring of claims,) and replace the original r.
 				}
```
Comment (silverwolfg11) [inline src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java:147]: Looking at it again, all of this can be probably be done in one go.
```java
int needed = pos.getTownBlock().hasTown() ? 0 : 1;
int claimRadius = 1;
while (claimRadius <= r && needed < available) {
    needed += (claimRadius * 8)
    claimRadius++;
}
// Claim Radius will always overshoot by 1
r = claimRadius - 1;
```

File: src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java [hunk 8]
```diff
@@ -72,101 +86,178 @@
...
+
+			/*
+			 * Adds WorldCoords in a spiral-out pattern.
+			 */
+			int sideLength = (r * 2) + 1;
+			int x = 0, z = 0, dx = 0, dz = -1;
+			int t = r;
+			for (int i = 0; i <= available; i++) {
+				if ((-sideLength / 2 <= x) && (x <= sideLength / 2) && (-sideLength / 2 <= z) && (z <= sideLength / 2)) {
+					out.add(new WorldCoord(pos.getWorldName(), pos.add(x, z)));
```
Comment (silverwolfg11) [inline src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java:158]: `pos.add()` returns a new worldcoord, so this entire line can be replaced with `out.add(pos.add(x,z));`

File: src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java [hunk 9]
```diff
@@ -72,101 +86,178 @@
...
-				if (r > TownySettings.getMaxClaimRadiusValue() && TownySettings.getMaxClaimRadiusValue() > 0) {
-					throw new TownyException(Translation.of("msg_err_invalid_radius_number", TownySettings.getMaxClaimRadiusValue()));
+			}
+
+			/*
+			 * Adds WorldCoords in a spiral-out pattern.
+			 */
+			int sideLength = (r * 2) + 1;
+			int x = 0, z = 0, dx = 0, dz = -1;
+			int t = r;
```
Comment (silverwolfg11) [inline src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java:155]: `t` seems to be used purely to swap variables, so it should only be in that scope.

File: src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java [hunk 10]
```diff
@@ -72,101 +86,178 @@
...
-						if (out.size() < available) {
-							WorldCoord wc = new WorldCoord(pos.getWorldName(), pos.getX() + x, pos.getZ() + z);
-							if (!wc.hasTownBlock())
-								out.add(wc);
-						}
-			} else {
-				throw new TownyException(Translation.of("msg_err_invalid_radius"));
+
+				if ((x == z) || ((x < 0) && (x == -z)) || ((x > 0) && (x == 1 - z))) {
+					t = dx;
```
Comment (silverwolfg11) [inline src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java:162]: Create a variable `swap` here to clarify intentions.

File: src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java [hunk 11]
```diff
@@ -72,101 +86,178 @@
...
+					r--; // Finally reduce the radius by 1 (so that we have a perfect ring of claims,) and replace the original r.
 				}
-				if (r > TownySettings.getMaxClaimRadiusValue() && TownySettings.getMaxClaimRadiusValue() > 0) {
-					throw new TownyException(Translation.of("msg_err_invalid_radius_number", TownySettings.getMaxClaimRadiusValue()));
+			}
+
+			/*
+			 * Adds WorldCoords in a spiral-out pattern.
+			 */
+			int sideLength = (r * 2) + 1;
```
Comment (silverwolfg11) [inline src/com/palmergames/bukkit/towny/utils/AreaSelectionUtil.java:153]: Might be worth it to divide by two in the initialization that consistently dividing by two in the for-loop.
